// -----------------------------------------------------------------------------
// BAG Protocol — domain types for the paper-trading / points / collectible loop.
//
// These are additive to the existing `types/index.ts` (Bag, CreatorProfile,
// User for the strategy-marketplace side of the app) and cover the parts of
// the spec that are new: trading, points, seasons, leaderboard, boxes,
// accessories/inventory and off-chain BAG NFTs.
// -----------------------------------------------------------------------------

// ----------------------------- Market ---------------------------------------

export const TRADABLE_SYMBOLS = [
  'BTC',
  'ETH',
  'SOL',
  'BNB',
  'XRP',
  'DOGE',
  'LINK',
  'AVAX',
] as const;

export type TradableSymbol = (typeof TRADABLE_SYMBOLS)[number];

// ----------------------------- Portfolio / Trading ---------------------------

export interface Position {
  symbol: string;
  quantity: number;
  /** Volume-weighted average cost basis per unit, in USD. */
  avgCost: number;
}

export interface Portfolio {
  userId: string;
  cashBalance: number;
  positions: Position[];
  /** Sum of realizedPnL across every closed/partial-close trade. */
  realizedPnL: number;
  /**
   * Phase 18.9 — monotonic counter, incremented by exactly 1 on every
   * successful `commit_investment_transaction()` write (see that RPC in
   * supabase/schema.sql). Replaces a cash-balance-only staleness check: two
   * commits that happen to leave `cashBalance` unchanged (e.g. a BUY
   * roughly offsetting an unrelated SELL) but that DID change `positions`
   * are still correctly detected as stale, because this always changes on
   * every commit regardless of what it did financially. A commit's
   * `expectedPortfolioVersion` must equal the CURRENT row's version under
   * lock, or the RPC raises `PORTFOLIO_STALE` and writes nothing.
   */
  portfolioVersion: number;
  createdAt: string;
  updatedAt: string;
}

export type TradeSide = 'BUY' | 'SELL';

export interface Trade {
  id: string;
  userId: string;
  symbol: string;
  side: TradeSide;
  quantity: number;
  price: number;
  totalValue: number;
  /** Only non-zero on SELL trades that close/reduce a position. */
  realizedPnL: number;
  /** Present when the trade was generated by investing into a BAG. */
  bagId?: string;
  /** Idempotency key — prevents the same client-submitted trade from posting twice. */
  clientTradeId?: string;
  createdAt: string;
}

export interface TradeResult {
  ok: boolean;
  error?: string;
  trade?: Trade;
  portfolio?: Portfolio;
  pointsAwarded?: number;
}

// ----------------------------- Points ----------------------------------------

export type PointTransactionType = 'TRADE_PROFIT' | 'BOX_PURCHASE' | 'ADMIN_ADJUSTMENT';

export interface PointTransaction {
  id: string;
  userId: string;
  seasonId: string;
  type: PointTransactionType;
  amount: number;
  referenceId?: string;
  createdAt: string;
}

export interface UserPoints {
  userId: string;
  seasonId: string;
  totalRealizedPnL: number;
  bagPoints: number;
  pointsSpent: number;
  pointsAvailable: number;
}

// ----------------------------- Season ----------------------------------------

export type SeasonStatus = 'UPCOMING' | 'ACTIVE' | 'ENDED';

export interface Season {
  id: string;
  name: string;
  startDate: string;
  endDate: string;
  status: SeasonStatus;
  topUsersReward: number;
}

// ----------------------------- Leaderboard ------------------------------------

export interface LeaderboardEntry {
  rank: number;
  userId: string;
  displayName: string;
  realizedPnL: number;
  bagPoints: number;
  isSelf?: boolean;
}

export interface LeaderboardResult {
  seasonId: string;
  entries: LeaderboardEntry[];
  topN: number;
  self: {
    rank: number;
    bagPoints: number;
    realizedPnL: number;
    pointsToNextRank: number;
  } | null;
}

// ----------------------------- Collectibles: Boxes -----------------------------

export type BoxTypeId = 'COMMON' | 'RARE' | 'EPIC';

export interface BoxTypeConfig {
  id: BoxTypeId;
  name: string;
  cost: number;
}

export interface Box {
  id: string;
  userId: string;
  boxType: BoxTypeId;
  opened: boolean;
  createdAt: string;
  openedAt?: string;
  resultAccessoryId?: string;
}

// ----------------------------- Collectibles: Accessories -----------------------

export const ACCESSORY_SLOTS = [
  'HEAD',
  'FACE',
  'NECK',
  'BODY',
  'BACK',
  'HANDS',
  'FEET',
  'SPECIAL',
] as const;

export type AccessorySlot = (typeof ACCESSORY_SLOTS)[number];

export type Rarity = 'COMMON' | 'UNCOMMON' | 'RARE' | 'EPIC' | 'LEGENDARY';

export interface Accessory {
  id: string;
  name: string;
  slot: AccessorySlot;
  rarity: Rarity;
  /** Emoji/glyph used as a lightweight stand-in for real artwork in the MVP. */
  image: string;
  metadata: Record<string, unknown>;
}

export interface InventoryItem {
  userId: string;
  accessoryId: string;
  quantity: number;
}

// ----------------------------- BAG NFT ------------------------------------------

export type BlockchainStatus = 'OFFCHAIN' | 'MINTED';

export interface BagNFT {
  id: string;
  ownerId: string;
  seasonId: string;
  rarity: Rarity;
  accessories: Record<AccessorySlot, string>; // slot -> accessoryId
  genesisRank?: number;
  createdAt: string;
  blockchainStatus: BlockchainStatus;
}

// ----------------------------- Activity typed helpers ---------------------------

export type DomainActivityType =
  | 'BAG_CREATED'
  | 'BAG_FORKED'
  | 'POINTS_EARNED'
  | 'BOX_OPENED'
  | 'NFT_ASSEMBLED'
  | 'TRADE_EXECUTED';
