import { Bag, User } from '@/types';

export const mockBags: Bag[] = [
  {
    id: '1',
    name: 'AI Leaders',
    category: 'AI',
    creator: {
      name: 'Protocol Labs',
      handle: 'protocollabs',
      avatar: '🤖',
      address: '0x82...41A',
      verified: true,
      creatorScore: 91,
      followers: 2400,
      forks: 340,
    },
    description: 'Exposure to leading AI and machine learning companies',
    thesis: 'AI is reshaping industries at an unprecedented pace. This bag focuses on companies at the forefront of AI innovation, from semiconductor leaders to software pioneers.',
    tvl: 245000000,
    followers: 2400,
    forks: 340,
    performance7d: 12.5,
    performance30d: 28.4,
    performanceYtd: 45.2,
    chains: ['Ethereum', 'Base', 'Arbitrum'],
    composition: [
      { symbol: 'NVIDIA', weight: 40 },
      { symbol: 'MSFT', weight: 30 },
      { symbol: 'TSLA', weight: 20 },
      { symbol: 'META', weight: 10 },
    ],
    rules: {
      rebalanceFrequency: 'Monthly',
      slippage: 5,
      minInvestment: 100,
    },
    social: { followers: 2400, forks: 340 },
    performance: { returnsYTD: 45.2 },
    updateLog: [
      {
        date: '2024-08-01',
        change: 'Added META position',
        reason: 'Increased AI investment exposure',
      },
      {
        date: '2024-07-15',
        change: 'Rebalanced NVIDIA position',
        reason: 'Market volatility management',
      },
    ],
  },
  {
    id: '2',
    name: 'L2 Ecosystem',
    category: 'L2',
    creator: {
      name: 'Arbitrum DAO',
      handle: 'arbitrum',
      avatar: '⚡',
      address: '0x93...5B2',
      verified: true,
      creatorScore: 85,
      followers: 1800,
      forks: 245,
    },
    description: 'Layer 2 solutions and ecosystem tokens',
    thesis: 'Layer 2 scaling solutions are essential for Ethereum. This bag captures the value accrual across leading L2 platforms.',
    tvl: 128000000,
    followers: 1800,
    forks: 245,
    performance7d: 8.3,
    performance30d: 15.7,
    performanceYtd: 32.1,
    chains: ['Ethereum', 'Arbitrum'],
    composition: [
      { symbol: 'ARB', weight: 35 },
      { symbol: 'OP', weight: 30 },
      { symbol: 'STRK', weight: 20 },
      { symbol: 'LINEA', weight: 15 },
    ],
    rules: {
      rebalanceFrequency: 'Bi-weekly',
      slippage: 3,
      minInvestment: 500,
    },
    social: { followers: 1800, forks: 245 },
    performance: { returnsYTD: 32.1 },
    updateLog: [
      {
        date: '2024-08-02',
        change: 'Added STRK position',
        reason: 'StarkNet momentum',
      },
    ],
  },
  {
    id: '3',
    name: 'RWA Index',
    category: 'RWA',
    creator: {
      name: 'Tokenize Labs',
      avatar: '🏢',
      address: '0x71...8C3',
      creatorScore: 74,
      followers: 1200,
      forks: 156,
    },
    description: 'Real-world asset tokenization leaders',
    thesis: 'Tokenization of real-world assets is the next frontier. This bag includes companies building infrastructure for RWA markets.',
    tvl: 89000000,
    followers: 1200,
    forks: 156,
    performance7d: 5.2,
    performance30d: 12.3,
    performanceYtd: 28.5,
    chains: ['Ethereum', 'Base'],
    composition: [
      { symbol: 'ONDO', weight: 40 },
      { symbol: 'MKR', weight: 30 },
      { symbol: 'LDO', weight: 20 },
      { symbol: 'GHO', weight: 10 },
    ],
    rules: {
      rebalanceFrequency: 'Monthly',
      slippage: 2,
      minInvestment: 1000,
    },
    social: { followers: 1200, forks: 156 },
    performance: { returnsYTD: 28.5 },
    updateLog: [],
  },
];

export const mockUser: User = {
  address: '0x82...41A',
  balance: 125000,
  network: 'Robinhood Chain Testnet',
  myBags: 3,
  following: 12,
  followers: 340,
  forks: 7,
  joinedAt: '2025-11-02',
  reputation: 92,
};

export const mockUserBags: Bag[] = [
  mockBags[0],
  mockBags[1],
  {
    ...mockBags[2],
    id: '4',
    name: 'My Custom Bag',
    creator: {
      name: 'You',
      avatar: '👤',
      address: '0x82...41A',
      followers: 45,
      forks: 12,
    },
  },
];
